### PR TITLE
Use of GitHub action

### PR DESCRIPTION
**Pull request by tomkimsour**
As the azure pipeline has not been working for a while I thought about trying the github actions and publish an artifact of the file

### CODE REVIEW

**Comment by tomkimsour** [comment]
I'll change dockerfile name to yours if you agree on this change and once I'm sure the pipeline is correct

**Comment by awesomebytes** [comment]
This is fantastic work!
I'm very happy to merge it whenever you think it's ready (I see you have some jobs running, I think they should work correctly once to be sure).

I can also give you access to these repos to co-maintain them if you'd like.

**Comment by awesomebytes** [comment]
Did you also see this PR in the brother repo?

https://github.com/awesomebytes/gentoo_prefix_ci/pull/9

Could you evaluate which approach is better?
* Easier to maintain
* More efficient

I'm sorry I don't use these actively anymore and I don't have that much free time for these projects. Your help is greatly appreciated.

**Comment by tomkimsour** [comment]
The way he did it is pretty clean, it's more about how you want it to be done. i'd say his is easier to maintain and easy to read. However it's not something we can do for the 32b version. Because of the architecture we are forced to put everything inside a docker container and compile them one by one.

Also he uses github registry instead of docker hub. There is not much difference over the two we just have to make a choice between having everything accessible from the repo page or not.

I'm not sure my implementation is the best. There is certainly some room for improvement.

**Comment by tomkimsour** [comment]
Having registries on github should be the right thing to do so that we don't have to change image name from one person testing to another. I'll make the change later.

**Comment by tomkimsour** [comment]
Looks like I'm ending up with a similar error you had in your pipeline for a while. I'm not sure how to go from this. It compiled fine on my local machine.

**Comment by awesomebytes** [comment]
Seems like you got an error that's just part of gentoo:
```
 #8 5106.2  * Error: circular dependencies:
#8 5106.2 
#8 5106.2 (net-libs/nghttp2-1.52.0:0/1.14::gentoo, ebuild scheduled for merge) depends on
#8 5106.2  (dev-util/cmake-3.25.3:0/0::gentoo, ebuild scheduled for merge) (buildtime)
#8 5106.2   (net-misc/curl-7.88.1-r1:0/0::gentoo, ebuild scheduled for merge) (buildtime)
#8 5106.2    (net-libs/nghttp2-1.52.0:0/1.14::gentoo, ebuild scheduled for merge) (buildtime_slot_op)
#8 5106.2 
#8 5106.2 It might be possible to break this cycle
#8 5106.2 by applying the following change:
#8 5106.2 - net-misc/curl-7.88.1-r1 (Change USE: -http2)
```

These things sometimes come and go (you trigger a build at a time there are changes happening upstream that may be halfway done). But if they stay for a bit, I usually open a bug report.

**Comment by tomkimsour** [comment]
Everything should be good now except artifact creation.
Containers are going to be stored on the repository if they build.
I removed the azure pipeline file.
There are 2 actions, one to test the last step of wrapping and extracting the tar file (this is mainly for faster test). The other is doing everything including extracting the file.
Normally the build should run everyday at 13:00 UTC
I updated the readme as well to show the state of github action and remove everything related to azure pipeline.

I would recommand to merge squash to main once everything if you find it good as there is a bunch of crap commit.

**Review by awesomebytes — APPROVED** [review]
LGTM and I believe you've tested it a fair amount, so let's give it a go (it's for sure better than it being broken)

**Pull request merged**
